name: Generate Starred README by Topic

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install starred
        run: pip install git+https://github.com/elgw/starred

      - name: Generate README.md by topic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          starred --username ${{ github.actor }} --token $GITHUB_TOKEN --sort topic --output README.md

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "chore: update starred repositories list (by topic)" || exit 0
          git push
