name: update awesome-stars (by topic)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  awesome-stars:
    name: update awesome-stars by topic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install starred
        run: python -m pip install --upgrade pip && pip install starred

      - name: Get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Update repo category by topic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          starred --username ${USERNAME} --repository ${REPOSITORY} --token ${GITHUB_TOKEN} --topic --sort --message 'awesome-stars category by topic update by github actions cron, created by starred'

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "chore: update starred repositories list (by topic)" || exit 0
          git push
